import { IMovie } from "./models/Movie";

export const data: IMovie[] = [
  {
    _id: '22',
    title: 'Great Wall',
    rating: 8.6,
    year: 2022,
    type: 'Movie',
    status: 'Realesed',
    qualities: ['1080HD', 'DBRip', '4K ULTRA'],
    description: 'В центре сюжета находится мрачная и немногословная Уэнсдэй — старшая дочь эксцентричной семейки Аддамс, которая из-за своих шокирующих выходок поменяла восемь школ за пять лет. После очередного скандального инцидента она вынуждена перевестись в Невермор — академию для изгоев, которую когда-то посещали ее родители. Учебным заведением железной хваткой руководит Ларисса Уимс — заклятый враг ее матери Мортиши. Здесь девушка развивает свои недавно открывшиеся экстрасенсорные способности и берется остановить блуждающего по округе монстра, охотящегося на людей.',
    actors: ['Nataly Portman', 'Bred Pitt', 'Leonardo Dicaprio'],
    genres: ['Drama', 'Fantasy', 'Travel'],
    poster: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/adventure-movie-poster-template-design-7b13ea2ab6f64c1ec9e1bb473f345547_screen.jpg?ts=1636999411',
    background: 'https://images6.alphacoders.com/569/569711.png',
  },
  {
    _id: '22',
    title: 'Title',
    rating: 0,
    year: 2022,
    type: 'Movie',
    status: 'Realesed',
    qualities: ['1080HD', 'DBRip', '4K ULTRA'],
    description: 'Title',
    actors: ['Roman', 'Nikolas', 'Nataly'],
    genres: ['Roman', 'Nikolas', 'Nataly'],
    poster: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/adventure-movie-poster-template-design-7b13ea2ab6f64c1ec9e1bb473f345547_screen.jpg?ts=1636999411',
    background: 'https://images6.alphacoders.com/569/569711.png',
  },
  {
    _id: '22',
    title: 'Title',
    rating: 6,
    year: 2022,
    type: 'Movie',
    status: 'Realesed',
    qualities: ['1080HD', 'DBRip', '4K ULTRA'],
    description: 'Title',
    actors: ['Roman', 'Nikolas', 'Nataly'],
    genres: ['Roman', 'Nikolas', 'Nataly'],
    poster: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/adventure-movie-poster-template-design-7b13ea2ab6f64c1ec9e1bb473f345547_screen.jpg?ts=1636999411',
    background: 'https://images6.alphacoders.com/569/569711.png',
  },
  {
    _id: '22',
    title: 'Avengers: Final',
    rating: 9,
    year: 2022,
    type: 'Movie',
    status: 'Realesed',
    qualities: ['1080HD', 'DBRip', '4K ULTRA'],
    description: 'В центре сюжета находится мрачная и немногословная Уэнсдэй — старшая дочь эксцентричной семейки Аддамс, которая из-за своих шокирующих выходок поменяла восемь школ за пять лет. После очередного скандального инцидента она вынуждена перевестись в Невермор — академию для изгоев, которую когда-то посещали ее родители. Учебным заведением железной хваткой руководит Ларисса Уимс — заклятый враг ее матери Мортиши. Здесь девушка развивает свои недавно открывшиеся экстрасенсорные способности и берется остановить блуждающего по округе монстра, охотящегося на людей.',
    actors: ['Roman', 'Nikolas', 'Nataly'],
    genres: ['Roman', 'Nikolas', 'Nataly'],
    poster: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/adventure-movie-poster-template-design-7b13ea2ab6f64c1ec9e1bb473f345547_screen.jpg?ts=1636999411',
    background: 'https://images6.alphacoders.com/569/569711.png',
  },
  {
    _id: '22',
    title: 'Title',
    rating: 0,
    year: 2022,
    type: 'Movie',
    status: 'Realesed',
    qualities: ['1080HD', 'DBRip', '4K ULTRA'],
    description: 'Title',
    actors: ['Roman', 'Nikolas', 'Nataly'],
    genres: ['Roman', 'Nikolas', 'Nataly'],
    poster: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/adventure-movie-poster-template-design-7b13ea2ab6f64c1ec9e1bb473f345547_screen.jpg?ts=1636999411',
    background: 'https://images6.alphacoders.com/569/569711.png',
  },
  {
    _id: '22',
    title: 'Title',
    rating: 0,
    year: 2022,
    type: 'Movie',
    status: 'Realesed',
    qualities: ['1080HD', 'DBRip', '4K ULTRA'],
    description: 'Title',
    actors: ['Roman', 'Nikolas', 'Nataly'],
    genres: ['Roman', 'Nikolas', 'Nataly'],
    poster: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/adventure-movie-poster-template-design-7b13ea2ab6f64c1ec9e1bb473f345547_screen.jpg?ts=1636999411',
    background: 'https://images6.alphacoders.com/569/569711.png',
  },
  {
    _id: '22',
    title: 'Title',
    rating: 0,
    year: 2022,
    type: 'Movie',
    status: 'Premiere',
    qualities: ['1080HD', 'DBRip', '4K ULTRA'],
    description: 'Title',
    actors: ['Roman', 'Nikolas', 'Nataly'],
    genres: ['Roman', 'Nikolas', 'Nataly'],
    poster: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/adventure-movie-poster-template-design-7b13ea2ab6f64c1ec9e1bb473f345547_screen.jpg?ts=1636999411',
    background: 'https://images6.alphacoders.com/569/569711.png',
  },
  {
    _id: '22',
    title: 'Title',
    rating: 0,
    year: 2022,
    type: 'Movie',
    status: 'Ongoing',
    qualities: ['1080HD', 'DBRip', '4K ULTRA'],
    description: 'Title',
    actors: ['Roman', 'Nikolas', 'Nataly'],
    genres: ['Roman', 'Nikolas', 'Nataly'],
    poster: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/adventure-movie-poster-template-design-7b13ea2ab6f64c1ec9e1bb473f345547_screen.jpg?ts=1636999411',
    background: 'https://images6.alphacoders.com/569/569711.png',
  },
  {
    _id: '22',
    title: 'Title',
    rating: 0,
    year: 2022,
    type: 'Movie',
    status: 'Premiere',
    qualities: ['1080HD', 'DBRip', '4K ULTRA'],
    description: 'Title',
    actors: ['Roman', 'Nikolas', 'Nataly'],
    genres: ['Roman', 'Nikolas', 'Nataly'],
    poster: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/adventure-movie-poster-template-design-7b13ea2ab6f64c1ec9e1bb473f345547_screen.jpg?ts=1636999411',
    background: 'https://images6.alphacoders.com/569/569711.png',
  },
  {
    _id: '22',
    title: 'Title',
    rating: 0,
    year: 2022,
    type: 'Movie',
    status: 'Realesed',
    qualities: ['1080HD', 'DBRip', '4K ULTRA'],
    description: 'Title',
    actors: ['Roman', 'Nikolas', 'Nataly'],
    genres: ['Roman', 'Nikolas', 'Nataly'],
    poster: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/adventure-movie-poster-template-design-7b13ea2ab6f64c1ec9e1bb473f345547_screen.jpg?ts=1636999411',
    background: 'https://images6.alphacoders.com/569/569711.png',
  },
]